package academy.cheerlot.config;

import academy.cheerlot.team.Team;
import academy.cheerlot.team.TeamRepository;
import academy.cheerlot.player.Player;
import academy.cheerlot.player.PlayerRepository;
import academy.cheerlot.cheersong.CheerSong;
import academy.cheerlot.cheersong.CheerSongRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.List;

@Component
@RequiredArgsConstructor
@Slf4j
@Profile("!test")
public class RedisDataLoader implements CommandLineRunner {

    private final TeamRepository teamRepository;
    private final PlayerRepository playerRepository;
    private final CheerSongRepository cheerSongRepository;

    @Override
    public void run(String... args) throws Exception {
        try {
            loadInitialData();
            log.info("✅ Redis initial data loading completed");
        } catch (Exception e) {
            log.error("❌ Failed to load initial data to Redis: {}", e.getMessage());
        }
    }

    private void loadInitialData() {
        if (teamRepository.count() > 0) {
            log.info("Redis already has team data, skipping initialization");
            return;
        }

        loadTeamData();
        loadPlayerData();
        loadCheerSongData();

        log.info("🚀 Loaded {} teams, {} players, and {} cheer songs into Redis", 
                teamRepository.count(), playerRepository.count(), cheerSongRepository.count());
    }

    private void loadTeamData() {
        List<Team> teams = List.of(
            new Team("SS", "삼성", LocalDate.of(2025, 1, 1), "로딩 중..."),
            new Team("LG", "LG", LocalDate.of(2025, 1, 1), "로딩 중..."),
            new Team("HH", "한화", LocalDate.of(2025, 1, 1), "로딩 중..."),
            new Team("LT", "롯데", LocalDate.of(2025, 1, 1), "로딩 중..."),
            new Team("NC", "NC", LocalDate.of(2025, 1, 1), "로딩 중..."),
            new Team("SK", "SSG", LocalDate.of(2025, 1, 1), "로딩 중..."),
            new Team("OB", "두산", LocalDate.of(2025, 1, 1), "로딩 중..."),
            new Team("KT", "KT", LocalDate.of(2025, 1, 1), "로딩 중..."),
            new Team("WO", "키움", LocalDate.of(2025, 1, 1), "로딩 중..."),
            new Team("HT", "KIA", LocalDate.of(2025, 1, 1), "로딩 중...")
        );

        teamRepository.saveAll(teams);
        log.info("📝 Loaded {} teams", teams.size());
    }

    // 전체 선수 데이터 로드 (data.sql.backup에서 변환)
    private void loadPlayerData() {
        // 삼성 라이온즈 선수들
        List<Player> ssPlayers = List.of(
            new Player("강민성", "127", "교체 선수", "SS", "1"),
            new Player("강민호", "47", "교체 선수", "SS", "2"),
            new Player("강한울", "6", "교체 선수", "SS", "3"),
            new Player("공민규", "9", "교체 선수", "SS", "4"),
            new Player("구자욱", "5", "교체 선수", "SS", "5"),
            new Player("김도환", "24", "교체 선수", "SS", "6"),
            new Player("김민수", "12", "교체 선수", "SS", "7"),
            new Player("김상준", "125", "교체 선수", "SS", "8"),
            new Player("김성윤", "39", "교체 선수", "SS", "9"),
            new Player("김영웅", "30", "교체 선수", "SS", "0"),
            new Player("김재성", "2", "교체 선수", "SS", "0"),
            new Player("김재혁", "8", "교체 선수", "SS", "0"),
            new Player("김재형", "124", "교체 선수", "SS", "0"),
            new Player("김지찬", "58", "교체 선수", "SS", "0"),
            new Player("김태근", "108", "교체 선수", "SS", "0"),
            new Player("김태훈", "25", "교체 선수", "SS", "0"),
            new Player("김헌곤", "32", "교체 선수", "SS", "0"),
            new Player("디아즈", "0", "교체 선수", "SS", "0"),
            new Player("류지혁", "16", "교체 선수", "SS", "0"),
            new Player("박병호", "52", "교체 선수", "SS", "0"),
            new Player("박승규", "66", "교체 선수", "SS", "0"),
            new Player("박장민", "116", "교체 선수", "SS", "0"),
            new Player("박진우", "111", "교체 선수", "SS", "0"),
            new Player("심재훈", "38", "교체 선수", "SS", "0"),
            new Player("안주형", "14", "교체 선수", "SS", "0"),
            new Player("양도근", "68", "교체 선수", "SS", "0"),
            new Player("양우현", "53", "교체 선수", "SS", "0"),
            new Player("오현석", "103", "교체 선수", "SS", "0"),
            new Player("윤정빈", "31", "교체 선수", "SS", "0"),
            new Player("이병헌", "23", "교체 선수", "SS", "0"),
            new Player("이성규", "13", "교체 선수", "SS", "0"),
            new Player("이재현", "7", "교체 선수", "SS", "0"),
            new Player("이진용", "117", "교체 선수", "SS", "0"),
            new Player("이창용", "50", "교체 선수", "SS", "0"),
            new Player("이해승", "56", "교체 선수", "SS", "0"),
            new Player("전병우", "34", "교체 선수", "SS", "0"),
            new Player("차승준", "35", "교체 선수", "SS", "0"),
            new Player("함수호", "40", "교체 선수", "SS", "0"),
            new Player("홍현빈", "63", "교체 선수", "SS", "0"),
                new Player("조민성", "132", "교체 선수", "SS", "0"),
                new Player("강준서", "105", "교체 선수", "SS", "0"),
                new Player("주한울", "104", "교체 선수", "SS", "0"),
                new Player("김상민", "107", "교체 선수", "SS", "0"),
                new Player("차동영", "106", "교체 선수", "SS", "0"),
                new Player("박진우", "67", "교체 선수", "SS", "0")
        );
        playerRepository.saveAll(ssPlayers);
        log.info("👥 Loaded {} players for 삼성 라이온즈", ssPlayers.size());

        // LG 트윈스 선수들
        List<Player> lgPlayers = List.of(
            new Player("구본혁", "6", "교체 선수", "LG", "0"),
            new Player("김민수", "16", "교체 선수", "LG", "0"),
            new Player("김범석", "55", "교체 선수", "LG", "0"),
            new Player("김성우", "44", "교체 선수", "LG", "0"),
            new Player("김성진", "36", "교체 선수", "LG", "0"),
            new Player("김주성", "5", "교체 선수", "LG", "0"),
            new Player("김현수", "22", "교체 선수", "LG", "0"),
            new Player("김현종", "66", "교체 선수", "LG", "0"),
            new Player("문보경", "2", "교체 선수", "LG", "0"),
            new Player("문성주", "8", "교체 선수", "LG", "0"),
            new Player("문정빈", "53", "교체 선수", "LG", "0"),
            new Player("박관우", "64", "교체 선수", "LG", "0"),
            new Player("박동원", "27", "교체 선수", "LG", "0"),
            new Player("박해민", "17", "교체 선수", "LG", "0"),
            new Player("서영준", "60", "교체 선수", "LG", "0"),
            new Player("손용준", "52", "교체 선수", "LG", "0"),
            new Player("송찬의", "14", "교체 선수", "LG", "0"),
            new Player("신민재", "4", "교체 선수", "LG", "0"),
            new Player("안익훈", "15", "교체 선수", "LG", "0"),
            new Player("오스틴", "23", "교체 선수", "LG", "0"),
            new Player("오지환", "10", "교체 선수", "LG", "0"),
            new Player("이영빈", "7", "교체 선수", "LG", "0"),
            new Player("이주헌", "26", "교체 선수", "LG", "0"),
            new Player("이태훈", "65", "교체 선수", "LG", "0"),
            new Player("이한림", "0", "교체 선수", "LG", "0"),
            new Player("최승민", "62", "교체 선수", "LG", "0"),
            new Player("최원영", "3", "교체 선수", "LG", "0"),
            new Player("천성호", "59", "교체 선수", "LG", "0"),
            new Player("함창건", "24", "교체 선수", "LG", "0"),
            new Player("홍창기", "51", "교체 선수", "LG", "0")
        );
        playerRepository.saveAll(lgPlayers);
        log.info("👥 Loaded {} players for LG 트윈스", lgPlayers.size());

        // 한화 이글스 선수들  
        List<Player> hhPlayers = List.of(
            new Player("권광민", "17", "교체 선수", "HH", "0"),
            new Player("김건", "56", "교체 선수", "HH", "0"),
            new Player("김예준", "114", "교체 선수", "HH", "0"),
            new Player("김인환", "37", "교체 선수", "HH", "0"),
            new Player("김태연", "25", "교체 선수", "HH", "0"),
            new Player("노시환", "8", "교체 선수", "HH", "0"),
            new Player("노석진", "117", "교체 선수", "HH", "0"),
            new Player("리베라토", "0", "교체 선수", "HH", "0"),
            new Player("문현빈", "51", "교체 선수", "HH", "0"),
            new Player("박상언", "42", "교체 선수", "HH", "0"),
            new Player("박정현", "63", "교체 선수", "HH", "0"),
            new Player("배승수", "98", "교체 선수", "HH", "0"),
            new Player("송호정", "54", "교체 선수", "HH", "0"),
            new Player("신우재", "69", "교체 선수", "HH", "0"),
            new Player("심우준", "2", "교체 선수", "HH", "0"),
            new Player("안진", "39", "교체 선수", "HH", "0"),
            new Player("안치홍", "3", "교체 선수", "HH", "0"),
            new Player("유로결", "33", "교체 선수", "HH", "0"),
            new Player("유민", "97", "교체 선수", "HH", "0"),
            new Player("이도윤", "7", "교체 선수", "HH", "0"),
            new Player("이민재", "57", "교체 선수", "HH", "0"),
            new Player("이상혁", "9", "교체 선수", "HH", "0"),
            new Player("이승현", "60", "교체 선수", "HH", "0"),
            new Player("이원석", "50", "교체 선수", "HH", "0"),
            new Player("이재원", "20", "교체 선수", "HH", "0"),
            new Player("이지성", "106", "교체 선수", "HH", "0"),
            new Player("이진영", "10", "교체 선수", "HH", "0"),
            new Player("임종찬", "24", "교체 선수", "HH", "0"),
            new Player("장규현", "32", "교체 선수", "HH", "0"),
            new Player("정민규", "65", "교체 선수", "HH", "0"),
            new Player("조한민", "4", "교체 선수", "HH", "0"),
            new Player("채은성", "22", "교체 선수", "HH", "0"),
            new Player("최인호", "41", "교체 선수", "HH", "0"),
            new Player("최재훈", "13", "교체 선수", "HH", "0"),
            new Player("최준서", "94", "교체 선수", "HH", "0"),
            new Player("하주석", "16", "교체 선수", "HH", "0"),
            new Player("한경빈", "6", "교체 선수", "HH", "0"),
            new Player("한지윤", "67", "교체 선수", "HH", "0"),
            new Player("허관회", "12", "교체 선수", "HH", "0"),
            new Player("허인서", "59", "교체 선수", "HH", "0"),
            new Player("황영묵", "95", "교체 선수", "HH", "0"),
                new Player("손아섭", "31", "교체 선수", "HH", "0"),
                new Player("최원준", "105", "교체 선수", "HH", "0"),
                new Player("김해찬", "118", "교체 선수", "HH", "0")
        );
        playerRepository.saveAll(hhPlayers);
        log.info("👥 Loaded {} players for 한화 이글스", hhPlayers.size());

        // 롯데 자이언츠 선수들
        List<Player> ltPlayers = List.of(
            new Player("강승구", "39", "교체 선수", "LT", "0"),
            new Player("고승민", "2", "교체 선수", "LT", "0"),
            new Player("김대현", "100", "교체 선수", "LT", "0"),
            new Player("김동규", "121", "교체 선수", "LT", "0"),
            new Player("김동혁", "50", "교체 선수", "LT", "0"),
            new Player("김동현", "64", "교체 선수", "LT", "0"),
            new Player("김민성", "16", "교체 선수", "LT", "0"),
            new Player("김세민", "119", "교체 선수", "LT", "0"),
            new Player("나승엽", "51", "교체 선수", "LT", "0"),
            new Player("노진혁", "52", "교체 선수", "LT", "0"),
            new Player("박건우", "109", "교체 선수", "LT", "0"),
            new Player("박승욱", "53", "교체 선수", "LT", "0"),
            new Player("박재엽", "63", "교체 선수", "LT", "0"),
            new Player("박지훈", "108", "교체 선수", "LT", "0"),
            new Player("박건", "129", "교체 선수", "LT", "0"),
            new Player("박찬형", "60", "교체 선수", "LT", "0"),
            new Player("배인혁", "127", "교체 선수", "LT", "0"),
            new Player("백두산", "62", "교체 선수", "LT", "0"),
            new Player("레이예스", "29", "교체 선수", "LT", "0"),
            new Player("손성빈", "28", "교체 선수", "LT", "0"),
            new Player("손호영", "33", "교체 선수", "LT", "0"),
            new Player("신윤후", "3", "교체 선수", "LT", "0"),
            new Player("엄장윤", "123", "교체 선수", "LT", "0"),
            new Player("오창현", "114", "교체 선수", "LT", "0"),
            new Player("유강남", "27", "교체 선수", "LT", "0"),
            new Player("유태웅", "112", "교체 선수", "LT", "0"),
            new Player("윤동희", "91", "교체 선수", "LT", "0"),
            new Player("이상화", "113", "교체 선수", "LT", "0"),
            new Player("이인한", "54", "교체 선수", "LT", "0"),
            new Player("이주찬", "116", "교체 선수", "LT", "0"),
            new Player("이태경", "69", "교체 선수", "LT", "0"),
            new Player("이호준", "30", "교체 선수", "LT", "0"),
            new Player("윤수녕", "126", "교체 선수", "LT", "0"),
            new Player("장두성", "7", "교체 선수", "LT", "0"),
            new Player("전민재", "13", "교체 선수", "LT", "0"),
            new Player("전준우", "8", "교체 선수", "LT", "0"),
            new Player("정보근", "42", "교체 선수", "LT", "0"),
            new Player("정훈", "9", "교체 선수", "LT", "0"),
            new Player("조세진", "5", "교체 선수", "LT", "0"),
            new Player("최민규", "105", "교체 선수", "LT", "0"),
            new Player("최항", "14", "교체 선수", "LT", "0"),
            new Player("한승현", "35", "교체 선수", "LT", "0"),
            new Player("한태양", "6", "교체 선수", "LT", "0"),
                new Player("황성빈", "0", "교체 선수", "LT", "0")
        );
        playerRepository.saveAll(ltPlayers);
        log.info("👥 Loaded {} players for 롯데 자이언츠", ltPlayers.size());

        // NC 다이노스 선수들
        List<Player> ncPlayers = List.of(
            new Player("고승완", "60", "교체 선수", "NC", "0"),
            new Player("권희동", "36", "교체 선수", "NC", "0"),
            new Player("김동현", "103", "교체 선수", "NC", "0"),
            new Player("김범준", "66", "교체 선수", "NC", "0"),
            new Player("김세훈", "9", "교체 선수", "NC", "0"),
            new Player("김정호", "42", "교체 선수", "NC", "0"),
            new Player("김주원", "7", "교체 선수", "NC", "0"),
            new Player("김태호", "109", "교체 선수", "NC", "0"),
            new Player("김한별", "68", "교체 선수", "NC", "0"),
            new Player("김형준", "25", "교체 선수", "NC", "0"),
            new Player("김휘집", "44", "교체 선수", "NC", "0"),
            new Player("데이비슨", "24", "교체 선수", "NC", "0"),
            new Player("도태훈", "16", "교체 선수", "NC", "0"),
            new Player("박건우", "37", "교체 선수", "NC", "0"),
            new Player("박민우", "2", "교체 선수", "NC", "0"),
            new Player("박세혁", "10", "교체 선수", "NC", "0"),
            new Player("박시원", "53", "교체 선수", "NC", "0"),
            new Player("박성재", "102", "교체 선수", "NC", "0"),
            new Player("박영빈", "39", "교체 선수", "NC", "0"),
            new Player("박인우", "112", "교체 선수", "NC", "0"),
            new Player("박주찬", "113", "교체 선수", "NC", "0"),
            new Player("서호철", "5", "교체 선수", "NC", "0"),
            new Player("송승환", "8", "교체 선수", "NC", "0"),
            new Player("신민우", "117", "교체 선수", "NC", "0"),
            new Player("신성호", "118", "교체 선수", "NC", "0"),
            new Player("안인산", "119", "교체 선수", "NC", "0"),
            new Player("안중열", "1", "교체 선수", "NC", "0"),
            new Player("양가온솔", "120", "교체 선수", "NC", "0"),
            new Player("오영수", "34", "교체 선수", "NC", "0"),
            new Player("오태양", "6", "교체 선수", "NC", "0"),
            new Player("오장한", "105", "교체 선수", "NC", "0"),
            new Player("유재현", "125", "교체 선수", "NC", "0"),
            new Player("이한", "122", "교체 선수", "NC", "0"),
            new Player("장창훈", "93", "교체 선수", "NC", "0"),
            new Player("조창연", "127", "교체 선수", "NC", "0"),
            new Player("조효원", "129", "교체 선수", "NC", "0"),
            new Player("천재환", "23", "교체 선수", "NC", "0"),
            new Player("최보성", "130", "교체 선수", "NC", "0"),
            new Player("최정원", "14", "교체 선수", "NC", "0"),
            new Player("한석현", "33", "교체 선수", "NC", "0"),
            new Player("한재환", "35", "교체 선수", "NC", "0"),
                new Player("홍종표", "4", "교체 선수", "NC", "0"),
                new Player("최원준", "31", "교체 선수", "NC", "0"),
                new Player("이우성", "55", "교체 선수", "NC", "0")
        );
        playerRepository.saveAll(ncPlayers);
        log.info("👥 Loaded {} players for NC 다이노스", ncPlayers.size());

        // SSG 랜더스 선수들
        List<Player> skPlayers = List.of(
            new Player("고명준", "18", "교체 선수", "SK", "0"),
            new Player("김규민", "61", "교체 선수", "SK", "0"),
            new Player("김민식", "24", "교체 선수", "SK", "0"),
            new Player("김성민", "56", "교체 선수", "SK", "0"),
            new Player("김성욱", "47", "교체 선수", "SK", "0"),
            new Player("김성현", "6", "교체 선수", "SK", "0"),
            new Player("김수윤", "4", "교체 선수", "SK", "0"),
            new Player("김정민", "4", "교체 선수", "SK", "0"),
            new Player("김찬형", "5", "교체 선수", "SK", "0"),
            new Player("김창평", "64", "교체 선수", "SK", "0"),
            new Player("김태윤", "36", "교체 선수", "SK", "0"),
            new Player("류효승", "45", "교체 선수", "SK", "0"),
            new Player("박성한", "2", "교체 선수", "SK", "0"),
            new Player("박정빈", "58", "교체 선수", "SK", "0"),
            new Player("박지환", "1", "교체 선수", "SK", "0"),
            new Player("석정우", "52", "교체 선수", "SK", "0"),
            new Player("신범수", "25", "교체 선수", "SK", "0"),
            new Player("안상현", "10", "교체 선수", "SK", "0"),
            new Player("에레디아", "27", "교체 선수", "SK", "0"),
            new Player("오태곤", "37", "교체 선수", "SK", "0"),
            new Player("이승민", "9", "교체 선수", "SK", "0"),
            new Player("이원준", "93", "교체 선수", "SK", "0"),
            new Player("이율예", "32", "교체 선수", "SK", "0"),
            new Player("이정범", "31", "교체 선수", "SK", "0"),
            new Player("이지영", "59", "교체 선수", "SK", "0"),
            new Player("임근우", "68", "교체 선수", "SK", "0"),
            new Player("정준재", "3", "교체 선수", "SK", "0"),
            new Player("조형우", "20", "교체 선수", "SK", "0"),
            new Player("채현우", "15", "교체 선수", "SK", "0"),
            new Player("최윤석", "94", "교체 선수", "SK", "0"),
            new Player("최정", "14", "교체 선수", "SK", "0"),
            new Player("최준우", "7", "교체 선수", "SK", "0"),
            new Player("최지훈", "54", "교체 선수", "SK", "0"),
            new Player("하재훈", "13", "교체 선수", "SK", "0"),
            new Player("한유섬", "35", "교체 선수", "SK", "0"),
            new Player("현원회", "8", "교체 선수", "SK", "0"),
            new Player("홍대인", "97", "교체 선수", "SK", "0"),
                new Player("김수윤", "4", "교체 선수", "SK", "0"),
                new Player("장현진", "49", "교체 선수", "SK", "0")
        );
        playerRepository.saveAll(skPlayers);
        log.info("👥 Loaded {} players for SSG 랜더스", skPlayers.size());

        // 두산 베어스 선수들
        List<Player> obPlayers = List.of(
            new Player("강승호", "23", "교체 선수", "OB", "0"),
            new Player("강현구", "60", "교체 선수", "OB", "0"),
            new Player("김기연", "45", "교체 선수", "OB", "0"),
            new Player("김대한", "27", "교체 선수", "OB", "0"),
            new Player("김동준", "48", "교체 선수", "OB", "0"),
            new Player("김민석", "2", "교체 선수", "OB", "0"),
            new Player("김민혁", "10", "교체 선수", "OB", "0"),
            new Player("김인태", "33", "교체 선수", "OB", "0"),
            new Player("김재환", "32", "교체 선수", "OB", "0"),
            new Player("김준상", "94", "교체 선수", "OB", "0"),
            new Player("류현준", "11", "교체 선수", "OB", "0"),
            new Player("박계범", "14", "교체 선수", "OB", "0"),
            new Player("박민준", "26", "교체 선수", "OB", "0"),
            new Player("박성재", "15", "교체 선수", "OB", "0"),
            new Player("박준순", "52", "교체 선수", "OB", "0"),
            new Player("박준영", "16", "교체 선수", "OB", "0"),
            new Player("박지훈", "37", "교체 선수", "OB", "0"),
            new Player("양석환", "53", "교체 선수", "OB", "0"),
            new Player("양의지", "25", "교체 선수", "OB", "0"),
            new Player("여동건", "5", "교체 선수", "OB", "0"),
            new Player("오명진", "6", "교체 선수", "OB", "0"),
            new Player("이선우", "24", "교체 선수", "OB", "0"),
            new Player("이유찬", "13", "교체 선수", "OB", "0"),
            new Player("임종성", "3", "교체 선수", "OB", "0"),
            new Player("장승현", "22", "교체 선수", "OB", "0"),
            new Player("전다민", "9", "교체 선수", "OB", "0"),
            new Player("정수빈", "31", "교체 선수", "OB", "0"),
            new Player("조수행", "51", "교체 선수", "OB", "0"),
            new Player("천현재", "96", "교체 선수", "OB", "0"),
            new Player("추재현", "36", "교체 선수", "OB", "0"),
            new Player("케이브", "8", "교체 선수", "OB", "0"),
            new Player("홍성호", "34", "교체 선수", "OB", "0"),
                new Player("안재석", "62", "교체 선수", "OB", "0")
                );
        playerRepository.saveAll(obPlayers);
        log.info("👥 Loaded {} players for 두산 베어스", obPlayers.size());

        // KT wiz 선수들
        List<Player> ktPlayers = List.of(
            new Player("강민성", "5", "교체 선수", "KT", "0"),
            new Player("강백호", "50", "교체 선수", "KT", "0"),
            new Player("강현우", "55", "교체 선수", "KT", "0"),
            new Player("권동진", "52", "교체 선수", "KT", "0"),
            new Player("김민석", "97", "교체 선수", "KT", "0"),
            new Player("김민혁", "53", "교체 선수", "KT", "0"),
            new Player("김병준", "57", "교체 선수", "KT", "0"),
            new Player("김상수", "7", "교체 선수", "KT", "0"),
            new Player("김준태", "44", "교체 선수", "KT", "0"),
            new Player("김철호", "9", "교체 선수", "KT", "0"),
            new Player("문상철", "24", "교체 선수", "KT", "0"),
            new Player("박민석", "2", "교체 선수", "KT", "0"),
            new Player("박민석", "104", "교체 선수", "KT", "0"),
            new Player("배정대", "27", "교체 선수", "KT", "0"),
            new Player("송민섭", "28", "교체 선수", "KT", "0"),
            new Player("안치영", "8", "교체 선수", "KT", "0"),
            new Player("안현민", "23", "교체 선수", "KT", "0"),
            new Player("오서진", "25", "교체 선수", "KT", "0"),
            new Player("오윤석", "4", "교체 선수", "KT", "0"),
            new Player("오재일", "36", "교체 선수", "KT", "0"),
            new Player("유준규", "67", "교체 선수", "KT", "0"),
            new Player("윤준혁", "35", "교체 선수", "KT", "0"),
            new Player("이정훈", "33", "교체 선수", "KT", "0"),
            new Player("이호연", "34", "교체 선수", "KT", "0"),
            new Player("장성우", "22", "교체 선수", "KT", "0"),
            new Player("장준원", "56", "교체 선수", "KT", "0"),
            new Player("장진혁", "51", "교체 선수", "KT", "0"),
            new Player("조대현", "42", "교체 선수", "KT", "0"),
            new Player("천성호", "14", "교체 선수", "KT", "0"),
            new Player("최성민", "31", "교체 선수", "KT", "0"),
            new Player("허경민", "13", "교체 선수", "KT", "0"),
            new Player("황재균", "10", "교체 선수", "KT", "0"),
                new Player("김건형", "0", "교체 선수", "KT", "0"),
                new Player("스티븐슨", "3", "교체 선수", "KT", "0")
        );
        playerRepository.saveAll(ktPlayers);
        log.info("👥 Loaded {} players for KT wiz", ktPlayers.size());

        // 키움 히어로즈 선수들
        List<Player> woPlayers = List.of(
            new Player("강진성", "27", "교체 선수", "WO", "0"),
            new Player("고영우", "44", "교체 선수", "WO", "0"),
            new Player("권혁빈", "71", "교체 선수", "WO", "0"),
            new Player("김건희", "12", "교체 선수", "WO", "0"),
            new Player("김동엽", "38", "교체 선수", "WO", "0"),
            new Player("김동현", "47", "교체 선수", "WO", "0"),
            new Player("김병휘", "23", "교체 선수", "WO", "0"),
            new Player("김웅빈", "10", "교체 선수", "WO", "0"),
            new Player("김재현", "32", "교체 선수", "WO", "0"),
            new Player("김지성", "65", "교체 선수", "WO", "0"),
            new Player("김태진", "1", "교체 선수", "WO", "0"),
            new Player("박성빈", "56", "교체 선수", "WO", "0"),
            new Player("박수종", "14", "교체 선수", "WO", "0"),
            new Player("박주홍", "57", "교체 선수", "WO", "0"),
            new Player("박준형", "75", "교체 선수", "WO", "0"),
            new Player("박찬혁", "48", "교체 선수", "WO", "0"),
            new Player("박채울", "79", "교체 선수", "WO", "0"),
            new Player("변상권", "9", "교체 선수", "WO", "0"),
            new Player("서유신", "98", "교체 선수", "WO", "0"),
            new Player("송성문", "24", "교체 선수", "WO", "0"),
            new Player("송지후", "86", "교체 선수", "WO", "0"),
            new Player("심휘윤", "91", "교체 선수", "WO", "0"),
            new Player("양현종", "70", "교체 선수", "WO", "0"),
            new Player("어준서", "92", "교체 선수", "WO", "0"),
            new Player("여동욱", "93", "교체 선수", "WO", "0"),
            new Player("염승원", "39", "교체 선수", "WO", "0"),
            new Player("오선진", "60", "교체 선수", "WO", "0"),
            new Player("원성준", "33", "교체 선수", "WO", "0"),
            new Player("이명기", "34", "교체 선수", "WO", "0"),
            new Player("이승원", "26", "교체 선수", "WO", "0"),
            new Player("이용규", "15", "교체 선수", "WO", "0"),
            new Player("이원석", "17", "교체 선수", "WO", "0"),
            new Player("이재상", "5", "교체 선수", "WO", "0"),
            new Player("이주형", "2", "교체 선수", "WO", "0"),
            new Player("이형종", "36", "교체 선수", "WO", "0"),
            new Player("임병욱", "6", "교체 선수", "WO", "0"),
            new Player("임지열", "29", "교체 선수", "WO", "0"),
            new Player("장재영", "61", "교체 선수", "WO", "0"),
            new Player("전태현", "97", "교체 선수", "WO", "0"),
            new Player("주성원", "25", "교체 선수", "WO", "0"),
            new Player("최주환", "53", "교체 선수", "WO", "0"),
            new Player("카디네스", "4", "교체 선수", "WO", "0"),
                new Player("김리안", "37", "교체 선수", "WO", "0"),
                new Player("이주형", "58", "교체 선수", "WO", "0"),
                new Player("스톤 개렛", "26", "교체 선수", "WO", "0")
        );
        playerRepository.saveAll(woPlayers);
        log.info("👥 Loaded {} players for 키움 히어로즈", woPlayers.size());

        // KIA 타이거즈 선수들
        List<Player> htPlayers = List.of(
            new Player("강민제", "13", "교체 선수", "HT", "0"),
            new Player("고종욱", "57", "교체 선수", "HT", "0"),
            new Player("권다결", "20", "교체 선수", "HT", "0"),
            new Player("김규성", "14", "교체 선수", "HT", "0"),
            new Player("김도영", "5", "교체 선수", "HT", "0"),
            new Player("김민수", "4", "교체 선수", "HT", "0"),
            new Player("김석환", "35", "교체 선수", "HT", "0"),
            new Player("김선빈", "3", "교체 선수", "HT", "0"),
            new Player("김재현", "10", "교체 선수", "HT", "0"),
            new Player("김태군", "42", "교체 선수", "HT", "0"),
            new Player("김호령", "27", "교체 선수", "HT", "0"),
            new Player("나성범", "47", "교체 선수", "HT", "0"),
            new Player("박민", "2", "교체 선수", "HT", "0"),
            new Player("박재현", "36", "교체 선수", "HT", "0"),
            new Player("박정우", "15", "교체 선수", "HT", "0"),
            new Player("박찬호", "1", "교체 선수", "HT", "0"),
            new Player("변우혁", "29", "교체 선수", "HT", "0"),
            new Player("서건창", "58", "교체 선수", "HT", "0"),
            new Player("엄준현", "31", "교체 선수", "HT", "0"),
            new Player("오선우", "56", "교체 선수", "HT", "0"),
            new Player("오정환", "7", "교체 선수", "HT", "0"),
            new Player("위즈덤", "45", "교체 선수", "HT", "0"),
            new Player("윤도현", "9", "교체 선수", "HT", "0"),
            new Player("이준범", "11", "교체 선수", "HT", "0"),
            new Player("이창진", "8", "교체 선수", "HT", "0"),
            new Player("정해원", "64", "교체 선수", "HT", "0"),
            new Player("주효상", "22", "교체 선수", "HT", "0"),
            new Player("최정용", "23", "교체 선수", "HT", "0"),
            new Player("최형우", "34", "교체 선수", "HT", "0"),
            new Player("한승택", "26", "교체 선수", "HT", "0"),
            new Player("한준수", "55", "교체 선수", "HT", "0"),
            new Player("황대인", "52", "교체 선수", "HT", "0"),
                new Player("김선우", "16", "교체 선수", "HT", "0"),
                new Player("신명승", "42", "교체 선수", "HT", "0"),
                new Player("박상준", "5", "교체 선수", "HT", "0"),
                new Player("장시현", "11", "교체 선수", "HT", "0"),
                new Player("정현창", "12", "교체 선수", "HT", "0"),
                new Player("박헌", "67", "교체 선수", "HT", "0"),
                new Player("예진원", "8", "교체 선수", "HT", "0"),
                new Player("한승연", "37", "교체 선수", "HT", "0")
        );
        playerRepository.saveAll(htPlayers);
        log.info("👥 Loaded {} players for KIA 타이거즈", htPlayers.size());
    }

    // CheerSong 데이터
    private void loadCheerSongData() {
        List<CheerSong> cheerSongs = List.of(
            new CheerSong("SS:47:ss47", "기본응원가", "강민호 민호민호\n삼성 강민호 오오오오 강민호\n빠라 빰빰빰 빰빰빰빰 강민호", "ss47.mp3", "SS:47"),
            new CheerSong("SS:6:ss6", "기본응원가", "달려라 라이온즈 강한울\n날려라 라이온즈 강한울\n오오우워 워 워\n승리를 위해 간다 강한울", "ss6.mp3", "SS:6"),
            new CheerSong("SS:9:ss9", "기본응원가", "삼성의 공민규\n삼성의 공민규\n승리를 위하여\n오 공민규", "ss9.mp3", "SS:9"),
            new CheerSong("SS:5:ss5(1)", "기본응원가", "최강 삼성 구자욱\n치고 달려 구자욱\n시원하게 한방\n날려버려 구자욱", "ss5(1).mp3", "SS:5"),
            new CheerSong("SS:5:ss5(2)", "안타/달빛소년", "최강 삼성 안타 구자욱\n승리를 위해 구자욱\n워워우워어\n최강삼성 구자욱", "ss5(2).mp3", "SS:5"),
            new CheerSong("SS:24:ss24", "기본응원가", "김도환 김도환 화니화니 안타\n김도환 김도환 워우워우워", "ss24.mp3", "SS:24"),
            new CheerSong("SS:12:ss12", "기본응원가", "최강 삼성 김민수 워\n안타 홈런 워어어어 워\n최강 삼성 김민수 워\n삼 성 김민수", "ss12.mp3", "SS:12"),
            new CheerSong("SS:39:ss39", "기본응원가", "더 멀리 더 빨리 치고 달려라\n최강 삼성 김성윤 워어어어어\n더 멀리 더 빨리 치고 달려라\n최강 삼성 김성윤 워어어어어\n최강 삼성 김성윤 넌 할 수있어", "ss39.mp3", "SS:39"),
            new CheerSong("SS:30:ss30", "기본응원가", "최강 삼성 히어로 누구 김영웅\n승리의 안타를 날려라\n최강 삼성 히어로 누구 김영웅\n워어어어어어어", "ss30.mp3", "SS:30"),
            new CheerSong("SS:2:ss2", "기본응원가", "삼성 김재성 오오오 김재성\n승리를 위하여 한방 날려버려\n김재성 오오오 김재성\n삼성의 김재성", "ss2.mp3", "SS:2"),
            new CheerSong("SS:8:ss8", "기본응원가", "삼성 김재혁 워어어어어\n삼성의 승리를 위해 오 파이팅", "ss8.mp3", "SS:8"),
            new CheerSong("SS:58:ss58", "기본응원가", "삼성의 김지찬\n안타를 날려라\n삼성의 김지찬\n찬찬찬 김지찬", "ss58.mp3", "SS:58"),
            new CheerSong("SS:25:ss25", "기본응원가", "삼성 김태훈 워어우워\n안타 김태훈 워어우워어\n삼성 김태훈 워어우워\n홈런 김태훈 워어우워어", "ss25.mp3", "SS:25"),
            new CheerSong("SS:32:ss32", "기본응원가", "오오 삼성의 김헌곤\n오오 삼성의 김헌곤\n오오 승리를 위해\n안타 안타 김헌곤", "ss32.mp3", "SS:32"),
            new CheerSong("SS:0:ss0", "기본응원가", "라이온즈의 디아즈\n디아즈 오오 디아즈\n승리를 위해 디아즈\n디아즈 워어어어어 (VIVA!)", "ss0.mp3", "SS:0"),
            new CheerSong("SS:16:ss16", "기본응원가", "삼성 류지혁\n류지혁 워어어어\n날려버려 워어어어\n시원하고 화끈하게 류지혁 (가자!)\n류지혁 워어어어 삼성 류지혁\n최강 삼성 승리를 위해 류지혁", "ss16.mp3", "SS:16"),
            new CheerSong("SS:52:ss52", "기본응원가", "오오오오 홈런 오오오오 홈런\n라이온즈 박병호\n오오오 오오오오오오\n라이온즈 박병호", "ss52.mp3", "SS:52"),
            new CheerSong("SS:66:ss66", "기본응원가", "안타를 펑펑펑 오 날려라\n최강 삼성 박승규\n안타를 펑펑 펑 펑\n안타를 펑펑펑 박승규 예", "ss66.mp3", "SS:66"),
            new CheerSong("SS:38:ss38", "기본응원가", "삼성의 심재훈 삼성의 심재훈\n안타를 날려버려 삼성 심재훈\n삼성의 심재훈 삼성의 심재훈\n홈런을 날려버려 삼성 심재훈", "ss38.mp3", "SS:38"),
            new CheerSong("SS:14:ss14", "기본응원가", "삼성의 안주형 안타\n안주형 안타\n안주형 안타\n오오오오", "ss14.mp3", "SS:14"),
            new CheerSong("SS:53:ss53", "기본응원가", "삼성의 양우현 삼성의 양우현\n오오오 최강삼성 양우현\n삼성의 양우현 삼성의 양우현\n야이야이야이야이야", "ss53.mp3", "SS:53"),
            new CheerSong("SS:31:ss31", "기본응원가", "오오오오 윤정빈\n삼성의 윤정빈 오오오\n오오오오 윤정빈\n삼성의 승리를 위해", "ss31.mp3", "SS:31"),
            new CheerSong("SS:23:ss23", "기본응원가", "이병헌 삼성의 승리를 위해\n안타를 날려버려 오오오\n이병헌 삼성의 승리를 위해\n날려버려 이병허니", "ss23.mp3", "SS:23"),
            new CheerSong("SS:13:ss13", "기본응원가", "날려라 삼성 이성규 오 안타\n삼성 이성규 오 홈런\n최강 삼성 승리 위해\n날려라 삼성 이성규 오 파이팅", "ss13.mp3", "SS:13"),
            new CheerSong("SS:7:ss7", "기본응원가", "삼성의 이재현\n빼뱀 뺌빼배뱀 안타 빼뱀\n삼성의 이재현\n빼뱀 뺌빼배뱀 홈런 빼뱀", "ss7.mp3", "SS:7"),
            new CheerSong("SS:50:ss50", "기본응원가", "오 이창용\n최강삼성 이창용\n라이온즈 승리 위하여\n안타 이창용", "ss50.mp3", "SS:50"),
            new CheerSong("SS:56:ss56", "기본응원가", "삼성의 이해승\n날려해승 달려해승 삼성 이해승 헤이", "ss56.mp3", "SS:56"),
            new CheerSong("SS:34:ss34", "기본응원가", "삼성의 전병우 전병우\n삼성 전병우 안타를 호우 홈런을 호우\n날려라 승리를 향해", "ss34.mp3", "SS:34"),
            new CheerSong("LG:6:lg6", "기본응원가", "당차고 시원하게 달려라 LG 구본혁\n언제나 너!의 옆에 우리가 함께\n당차고 시원하게 날려라 LG 구본혁\n언제나 너! 영원히 사랑할게", "lg6.mp3", "LG:6"),
            new CheerSong("LG:16:lg16", "기본응원가", "안타 안타 LG 김민수\n안타 안타 LG 김민수\n안타 안타 LG 김민수\n오! 김민수", "lg16.mp3", "LG:16"),
            new CheerSong("LG:55:lg55", "기본응원가", "LG의 김범석\nLG의 김범석\nLG의 승리를 위하여\n날려라 김범석", "lg55.mp3", "LG:55"),
            new CheerSong("LG:22:lg22", "기본응원가", "오! LG의 김현수 x2\n오! 승리를 위하여\n오! 힘차게 날려라\n오! LG의 김현수 x2\n오! 승리를 위하여\n무! 적! L! G! 김! 현! 수!", "lg22.mp3", "LG:22"),
            new CheerSong("LG:2:lg2", "기본응원가", "무적LG 승리 위해 날려버려라\nLG의 문보경 (안타!) LG의 문보경 (홈런!)", "lg2.mp3", "LG:2"),
                new CheerSong("LG:2:lg2", "기본응원가", "오오오 문보경!\nLG의 문보경 (안타!)\nLG의 문보경 문보경\n안타를 날려라 (안타!)", "lg2(2).mp3", "LG:2"),
                new CheerSong("LG:8:lg8", "기본응원가", "무적LG 오 문성주 날려버려라\n무적LG 오 문성주 날려버려라\n랄랄라라 랄랄라라 랄랄랄라라 (헤이!)\n랄랄라라 랄랄라라 랄랄랄라라 (헤이!)", "lg8.mp3", "LG:8"),
                new CheerSong("LG:8:lg8", "기본응원가", "무적 LG 문성주\n무적 LG 문성주\n오오오오\\nLG의 문성주 날려버려라\n무적 LG 문성주\n무적 LG 문성주\n오오오오\nLG의 문성주 날려버려라\n 오오오오오\n문! 성! 주!", "lg8(2).mp3", "LG:8"),
                new CheerSong("LG:53:lg53", "기본응원가", "문정빈 힘차게 날아올라봐\nLG의 승리 위하여\n문정빈 넌 빛나고 있어\n문정빈 힘차게 날아올라봐\nLG의 승리 위하여\n문정빈 주인공은 바로 너!\n문!정!빈!", "lg53.mp3", "LG:53"),
                new CheerSong("LG:64:lg64", "기본응원가", "LG 박관우\n무적LG의 박관우\n무적 LG\n승리 위하여\n워어어어어어", "lg64.mp3", "LG:64"),
                new CheerSong("LG:27:lg27", "기본응원가", "시원하게 (쏴) 쏘아올려 (쏴)\n무적LG 박동원 (안타!)\n승리위해 저 끝까지\n날려버려 박동원 (홈런!)", "lg27.mp3", "LG:27"),
            new CheerSong("LG:17:lg17", "기본응원가", "날려버려 안타 박해민\n오오오오오 박해민\n무!적!L!G! 박!해!민!", "lg17.mp3", "LG:17"),
                new CheerSong("LG:5:lg5", "기본응원가", "오 LG 김주성\n오 LG 김주성\n오 LG 김주성\n워어어어어\n힘차게 달려가라\nLG 김주성", "lg5.mp3", "LG:5"),
                new CheerSong("LG:14:lg14", "기본응원가", "LG의 송찬의(안타!) LG의 송찬의(홈런!)\n무적LG 승리위해 날려버려라", "lg14.mp3", "LG:14"),
            new CheerSong("LG:4:lg4", "기본응원가", "날려버려 날려버려 안!타!신!민!재!", "lg4.mp3", "LG:4"),
            new CheerSong("LG:15:lg15", "기본응원가", "날려버려 LG의 안익훈\n승리위해 힘차게 날려라\n날려버려 LG의 안익훈 승리를 위해\n날려버려 LG의 안익훈\n승리위해 힘차게 날려라\n날려버려 LG의 안익훈\n무!적!L!G! 안!익!훈!", "lg15.mp3", "LG:15"),
            new CheerSong("LG:23:lg23(1)", "기본응원가", "무적LG의 오스틴 딘! 날려버려라 오! 스! 틴! 딘!", "lg23(1).mp3", "LG:23"),
            new CheerSong("LG:23:lg23(2)", "안타/홈런", "오스틴 딘 오오오 오스틴 딘 오오오 오스틴 딘 오오오 오!스!틴! 딘!", "lg23(2).mp3", "LG:23"),
            new CheerSong("LG:10:lg10", "기본응원가", "무적 LG 오지환\n무적 LG 오지환\n워어어어어어어\n(누구?)\n무!적!L!G! 오!지!환!", "lg10.mp3", "LG:10"),
            new CheerSong("LG:7:lg7", "기본응원가", "달려라 LG의 이영빈\n날려라 LG의 이영빈\nLG의 승리를 위하여\n오! 이영빈", "lg7.mp3", "LG:7"),
            new CheerSong("LG:26:lg26", "기본응원가", "트윈스 이주헌 날려버려라\n날려버려라 날려버려라\n트윈스 이주헌 날려버려라\nLG 트윈스의 주헌이 (안타!)", "lg26.mp3", "LG:26"),
            new CheerSong("LG:62:lg62", "기본응원가", "오 달려라 오 달려라\n날!쌘!돌!이! 최!승!민!", "lg62.mp3", "LG:62"),
            new CheerSong("LG:3:lg3", "기본응원가", "오 LG의 최원영 끝까지\n오 LG의 최원영 할!수!있!어!최!원!영!", "lg3.mp3", "LG:3"),
            new CheerSong("LG:59:lg59", "기본응원가", "LG 천성호 (호!) LG 천성호 (호!)\n무적 LG 승리를 위해 \n(안!타!천!성!호!)", "lg59.mp3", "LG:59"),
            new CheerSong("LG:51:lg51", "기본응원가", "홍창기 안타 안타날려 홍창기\n홍창기 안타 날려버려라\n홍창기 안타 안타날려 홍창기\n무적 LG의 승리를 위해", "lg51.mp3", "LG:51"),
            new CheerSong("HH:37:hh37", "기본응원가", "워어어 최강한화 김인환 워 승릴위해 외쳐라 (김!인!환!)\n워어어 최강한화 김인환 워어어 워어어어어 (김!인!환!)", "hh37.mp3", "HH:37"),
            new CheerSong("HH:8:hh8", "기본응원가", "오 노시환 워어어 워어어어 날려줘요 환상적으로 날려버려 노시환\n오 노시환 워어어 워어어어 날려줘요 환상적으로 안타 홈런 워어어어 노!시!환!", "hh8.mp3", "HH:8"),
            new CheerSong("HH:51:hh51", "기본응원가", "한화 문현빈 워어어어어 한화 문현빈 워어어어어\n최강 한화의 승리를 위해 워어어어 어어어어", "hh51.mp3", "HH:51"),
            new CheerSong("HH:42:hh42", "기본응원가", "한화의 박상언 워어어어 한화의 박상언 워어어어\n승리의 그이름 박상언 기억해 워어어어", "hh42.mp3", "HH:42"),
            new CheerSong("HH:2:hh2", "기본응원가", "한화 심우준 한화 심우준 오오오\n이글스의 심우준\n한화 심우준 한화 심우준 오오오\n너는 슈퍼 판타스틱", "hh2.mp3", "HH:2"),
            new CheerSong("HH:3:hh3", "기본응원가", "한화 안치홍 한화 안치홍 워어\n승리를 위하여 워어어 워어어", "hh3.mp3", "HH:3"),
            new CheerSong("HH:7:hh7", "기본응원가", "한화의(의!) 이도윤(윤!) 워어어어어어어 힘차게 날려라 승리를 위하여\n한화의(의!) 이도윤(윤!) 워어어어어어어 힘차게 날려라 이도윤 (이!도!윤!)", "hh7.mp3", "HH:7"),
            new CheerSong("HH:20:hh20", "기본응원가", "이글스의 이재원 오오오 오오오오\n이글스의 이재원 오오오 오오오오\n이재원 오오오오 오오오오 오오오오\n이글스의 이재원 오오오 오오오오 이!재!원!", "hh20.mp3", "HH:20"),
            new CheerSong("HH:10:hh10", "기본응원가", "한화의 이진영 워어어\n한화의 이진영 워어어\n이순간 너의 모든것을 보여줘 넌! 이진영이다", "hh10.mp3", "HH:10"),
            new CheerSong("HH:24:hh24", "기본응원가", "오 임종찬 짝짝 오 임종찬 짝짝 찬찬찬\n한화 임종찬 로컬보이 워 워워 한화 임종찬", "hh24.mp3", "HH:24"),
            new CheerSong("HH:22:hh22", "기본응원가", "최강한화 채은성 워어어어\n최강한화 채은성 워어어어\n저!하늘로 날아올라 빛이 되리라 워어어어 한화 채은성", "hh22.mp3", "HH:22"),
            new CheerSong("HH:41:hh41", "기본응원가", "호! 안타 최인호 안타 최인호 워어어어\n이글스의 호! 안타 최인호 안타 최인호 워어어어\n이글스의 최!인!호!", "hh41.mp3", "HH:41"),
            new CheerSong("HH:13:hh13", "기본응원가", "케세라세라 이글스의 승리 위해 워어\n안타 날려줘요 한방 날려줘요 이글스의 최재훈\n케세라세라 이글스의 승리 위해 워어\n안타 날려라 날려라 날려라 날려라 (최! 재! 훈!)", "hh13.mp3", "HH:13"),
            new CheerSong("HH:34:hh34", "기본응원가", "플로리얼 워어어어 한화의 플!로!리!얼! 워어 어어어", "hh34.mp3", "HH:34"),
            new CheerSong("HH:16:hh16", "기본응원가", "하주석 유후 하주석 승리를 위해 함께 외쳐라\n하주석 유후 하주석 승리를 위해 함께 외쳐라 워어\n하!주!석!", "hh16.mp3", "HH:16"),
            new CheerSong("HH:95:hh95", "기본응원가", "한화의 황영묵 날려버려라 한화의 승리를 원하잖아\n최강 한화의 승리를 위해 날려라 묵이\n황!영!묵!", "hh95.mp3", "HH:95"),
                new CheerSong("HH:50:hh50", "기본응원가", "한화의 이원석\n승리를 위하여\n치고 달려(우!아!우!아)\n이원석 여기서\n멈추지 않을거야\n간!다! 와다다다다다다다", "hh50.mp3", "HH:50"),
                new CheerSong("HH:31:hh31", "기본응원가", "오! 이글스의 손아섭\\n한화 승리 위해\\n오오 오오오\\n이!글!스!의! 손!아!섭!", "hh31.mp3", "HH:31"),
                new CheerSong("HH:0:hh0", "기본응원가", "리베라토 워어어어\n한화의 리!베!라!토!\n워어 어어어", "hh0.mp3", "HH:0"),
                new CheerSong("LT:2:lt2", "기본응원가", "롯데의 고승민 안타 안타 롯데의 고승민 안타 안타\n워어어 워어어 워어어어\n워어어 워어어 워어어어\n롯데의 고승민 안타 안타", "lt2.mp3", "LT:2"),
            new CheerSong("LT:50:lt50", "기본응원가", "롯데 자이언츠 김동혁 오오오오 김동혁\n롯데 자이언츠 김동혁 롯데 김동혁 오 오오오\n(안타! 김!동!혁!) X2", "lt50.mp3", "LT:50"),
            new CheerSong("LT:16:lt16", "기본응원가", "롯데의 김민성 오오 오오오 오오오 ×4", "lt16.mp3", "LT:16"),
            new CheerSong("LT:51:lt51", "기본응원가", "자이언츠! 나승엽 쌔리라! 안타 안타\n자이언츠! 나승엽 오오오오 오오오 ×2", "lt51.mp3", "LT:51"),
            new CheerSong("LT:52:lt52", "기본응원가", "롯데 노진혁 롯데 노진혁 오오오\n안타 홈런 오오오 오오오오\n안타 홈런 오오오 오오오오 ×2\n롯데 노진혁", "lt52.mp3", "LT:52"),
            new CheerSong("LT:53:lt53", "기본응원가", "롯데의 박승욱 안타 안타!\n롯데의 박승욱 안타 안타\n오오오 오오오 오오오 오오오\n롯!데! 박!승!욱! ×2", "lt53.mp3", "LT:53"),
            new CheerSong("LT:29:lt29", "기본응원가", "빅터 레이예스 안타홈런 오오오\n빅터 레이예스 오오오 오오\n빅터 레이예스 안타홈런 오오오\n빅터 레이예스 (롯데! 레이예스!) x2", "lt29.mp3", "LT:29"),
            new CheerSong("LT:28:lt28", "기본응원가", "최강롯데 자이언츠 롯데 손성빈!\n안타 손성빈! 안타 손성빈!\n오오오오 오오 손!성!빈! ×2", "lt28.mp3", "LT:28"),
            new CheerSong("LT:33:lt33", "기본응원가", "롯데의 손호영 안타 쎄리라\n롯데의 손호영 오오오오 ×4", "lt33.mp3", "LT:33"),
            new CheerSong("LT:3:lt3", "기본응원가", "롯데 신윤후 롯데 신윤후\n안타 안타 오오오오 ×2", "lt3.mp3", "LT:3"),
            new CheerSong("LT:27:lt27", "기본응원가", "롯데의 유강남 오오오 (유!강!남!)\n롯데의 유강남 오 오오오 ×2", "lt27.mp3", "LT:27"),
            new CheerSong("LT:91:lt91", "기본응원가", "롯데의 윤동희! 쌔리라 안타 쌔리라\n최강롯데 자이언츠! 윤동희 (안타!) X2", "lt91.mp3", "LT:91"),
            new CheerSong("LT:30:lt30", "기본응원가", "롯데 이호준 안타 쎄리라\n오오오오오 오 오오\n롯데 이호준 안타 안타\n롯데의 이호준 ×2", "lt30.mp3", "LT:30"),
            new CheerSong("LT:7:lt7", "기본응원가", "롯데 롯데 장두성 롯데의 장두성\n롯데 롯데 장두성 오 오오 오오오오오 안타! x2", "lt7.mp3", "LT:7"),
            new CheerSong("LT:13:lt13", "기본응원가", "롯데의 전민재 롯데의 전민재 안타 오오오오 오 오오 오\n롯데 전민재 (전민재!) 전민재 롯데의 전민재 안타\n오오오오 오 오오 오 롯데 전민재 (전민재!)", "lt13.mp3", "LT:13"),
            new CheerSong("LT:8:lt8", "기본응원가", "안타! 안타! 쌔리라 쌔리라\n롯!데 전준우\n안타! 안타! 쌔리라 쌔리라\n롯!데 전준우 ×2", "lt8.mp3", "LT:8"),
            new CheerSong("LT:42:lt42", "기본응원가", "롯데 자이언츠 정보근 (Hey!)\n롯데 자이언츠 정보근 (Hey!)\n롯데 자이언츠 정보근 (Hey!)\n오 오오 오오오 ×2", "lt42.mp3", "LT:42"),
            new CheerSong("LT:9:lt9", "기본응원가", "오! 정훈!(정훈! 정훈!) 자이언츠 정훈!\n오 오오오오 오오 오오오 x2 (날려버려!)", "lt9.mp3", "LT:9"),
            new CheerSong("LT:5:lt5", "기본응원가", "오오오 오오 오오오\n오 롯데 롯데 조세진\n오오오 오오 오오오\n오 롯데 롯데 조세진 x2", "lt5.mp3", "LT:5"),
            new CheerSong("LT:14:lt14", "기본응원가", "롯데의 최항 오오오오오 오오오\n최강롯데 자이언츠 최항 안타 ×4", "lt14.mp3", "LT:14"),
            new CheerSong("LT:6:lt6", "기본응원가", "롯데 자이언츠 한태양 안타\n오오 오오오오 오오오\n롯데 자이언츠 한태양 안타\n오오오 오 오오오 x2", "lt6.mp3", "LT:6"),
                new CheerSong("LT:60:lt60", "기본응원가", "오 롯데의 박찬형\n안타 안타 안타 안타\n오 롯데의 박찬형\n박!찬!형!", "lt60.mp3", "LT:60"),
                new CheerSong("NC:36:nc36", "기본응원가", "다이노스 오 권희동NC 오! 권희동 오! 권희동 권희동 안타 NC 오! 권희동 오! 권희동 오 오오오 권! 희! 동!NC 오! 권희동 오! 권희동 권희동 안타 NC 오! 권희동 오! 권희동 오 오오오 권! 희! 동!", "nc36.mp3", "NC:36"),
            new CheerSong("NC:7:nc7", "기본응원가", "다이노 김주원오 NC 김주원 힘차게 달려 라랄랄라 오오오 NC 김주원 승리를 위해 라랄라오 NC 김주원 힘차게 달려 라랄랄라 오오오 NC 김주원 승리를 위해 라랄라다이노스 김! 주! 원!", "nc7.mp3", "NC:7"),
            new CheerSong("NC:68:nc68", "기본응원가", "오오오 김한별 승리를 위하여 안타 치고 달려라 (김한별!)오오오 김한별 승리를 위하여 다이노스 김한별 날려라", "nc68.mp3", "NC:68"),
            new CheerSong("NC:25:nc25", "기본응원가", "오오오 NC 김형준! 오오 오오오오다이노스 승리를 위해 NC 김형준 (김!형!준!) X2", "nc25.mp3", "NC:25"),
            new CheerSong("NC:44:nc44", "기본응원가", "안타 안타 날려버려 다이노스 김휘집 (예!)", "nc44.mp3", "NC:44"),
            new CheerSong("NC:24:nc24", "기본응원가", "데이비슨 오오 데이비슨 오오오오 데이비슨 오오 NC 다이노스 데 이 비 슨!", "nc24.mp3", "NC:24"),
            new CheerSong("NC:16:nc16", "기본응원가", "다이노스 도태훈 안타 오! 오오오오 다이노스 도태훈 안타 오! 오오오오", "nc16.mp3", "NC:16"),
            new CheerSong("NC:37:nc37", "기본응원가", "워어어 NC 박건우 워어어 NC 박건우 언제나 거침없이 넌 달려왔지쎄리라 NC 박건우 쎄리라 NC 박건우 절대 멈추지 않아 승리를 향해 박건우", "nc37.mp3", "NC:37"),
            new CheerSong("NC:2:nc2(1)", "기본응원가", "오오오 박민우 오오오 박민우 오오오 날려버려 (안타!)", "nc2(1).mp3", "NC:2"),
            new CheerSong("NC:2:nc2(2)", "기본응원가", "오오오 NC의 박민우 오오오 NC의 박민우 오오오 NC의 박민우 다! 이! 노! 스! 박! 민! 우!", "nc2(2).mp3", "NC:2"),
            new CheerSong("NC:10:nc10", "기본응원가", "워어우워어어 NC 박세혁 워어우워어어 NC 박세혁워우워 안방마님 박세혁! 워우워 다이노스 박세혁!", "nc10.mp3", "NC:10"),
            new CheerSong("NC:53:nc53", "기본응원가", "다이노스 박시원 오오오오오오오오오오 (안! 타! 박시원!)다이노스 박시원 (시원하게 쌔리라!)", "nc53.mp3", "NC:53"),
            new CheerSong("NC:5:nc5", "기본응원가", "다이노스 서호철 워어어 워어 안! 타! 다이노스 서호철 승리를 위해 안! 타!", "nc5.mp3", "NC:5"),
            new CheerSong("NC:1:nc1", "기본응원가", "다이노스 안중열 거침없이 가자 가자 안중열 (안중열 안타!)다이노스 안중열 거침없이 안타 안타 안중열 (안중열 안타!)", "nc1.mp3", "NC:1"),
            new CheerSong("NC:34:nc34", "기본응원가", "오! 오영수 NC 다이노스 오영수안타를 (쌔리라!) 홈런을 (쌔리라!) 다! 이! 노! 스! 오! 영! 수!", "nc34.mp3", "NC:34"),
            new CheerSong("NC:23:nc23", "기본응원가", "다이노스 천재환 오오오 워어어어 다이노스 천재환 (안! 타! 천재환!)다이노스 천재환 오오오 워어어어 다이노스 천재환 (홈! 런! 천재환!)", "nc23.mp3", "NC:23"),
            new CheerSong("NC:14:nc14", "기본응원가", "다이노스 NC 최정원 안타 안타 날려버려 다이노스 NC 최정원 안타 오오오 최! 정! 원!", "nc14.mp3", "NC:14"),
            new CheerSong("NC:33:nc33", "기본응원가", "NC 한석현 NC 한석현 NC 한석현 거침없이 가! 자! NC 한석현 NC 한석현 NC 한석현 승리위해 안! 타!NC 한석현 NC 한석현 NC 한석현 오오오오 안! 타! NC 한석현 NC 한석현 NC 한석현 다이노스 한! 석! 현!", "nc33.mp3", "NC:33"),
                new CheerSong("NC:55:nc55", "기본응원가", "다이노스 이우성\n승리위해 날려라\n우리들의 별이 되어\n오 이우성\n안! 타! 이우성!\n홈! 런! 이우성!", "nc33.mp3", "NC:33"),
                new CheerSong("NC:31:nc31", "기본응원가", "오오오 최원준\n다이노스 최원준 안타\n우리들의 승리 위해\n치고 달려라\n오오오 최원준\n다이노스 최원준(안타! 안타!)\n오 최원준", "nc31.mp3", "NC:31"),
                new CheerSong("NC:4:nc4", "기본응원가", "다이노스! 홍종표\n꿈을 향해서\n다이노스 홍종표\n치고 달려라\n홍종표! 홍종표!\n꿈을 향해 달려라\n다이노스 홍종표!", "nc31.mp3", "NC:31"),
                new CheerSong("SK:18:sk18", "기본응원가", "아고명준 오오오 오(×3)랜더스의 고명준!×2", "sk18.mp3", "SK:18"),
            new CheerSong("SK:24:sk24", "기본응원가", "오! 김민식 안타 워 워어어어오! 김민식 안타 워어 워어어어×2", "sk24.mp3", "SK:24"),
            new CheerSong("SK:56:sk56", "기본응원가", "김성민 날려라 오오오오오김성민 오! 안타 날려라×2", "sk56.mp3", "SK:56"),
            new CheerSong("SK:6:sk6", "기본응원가", "랜더스의 김성현 날려버려 김성현아아아아아아아아 안타!오오오오오오오오 안타!×2", "sk6.mp3", "SK:6"),
            new CheerSong("SK:5:sk5", "기본응원가", "오! 안타 김찬형(짝짝)(×2)오오오오 랜더스 위해 안타 김찬형×2", "sk5.mp3", "SK:5"),
            new CheerSong("SK:64:sk64", "기본응원가", "김창평 안타 김창평 안타 랜더스의 김창평×4", "sk64.mp3", "SK:64"),
            new CheerSong("SK:2:sk2", "기본응원가", "박성한! 랜더스 위하여시원하게 날려라오오오 오오오오×2", "sk2.mp3", "SK:2"),
            new CheerSong("SK:1:sk1", "기본응원가", "오오오 랜더스 오오오 박지환 승리를 위하여안타 날려라 x2", "sk1.mp3", "SK:1"),
            new CheerSong("SK:25:sk25", "기본응원가", "열!쩡! 신범수 오오오오오(안타!) ×4", "sk25.mp3", "SK:25"),
            new CheerSong("SK:10:sk10", "기본응원가", "오오오 오오오 랜더스의 안상현오오오 오오오 치!고 달려라×2", "sk10.mp3", "SK:10"),
            new CheerSong("SK:27:sk27", "기본응원가", "랜더스 에레디아 안타 에헤라디아랜더스 에레디아 워우워어어×2에!레!디아!", "sk27.mp3", "SK:27"),
            new CheerSong("SK:37:sk37", "기본응원가", "오! 안타 오태곤 오오오 오오오오! 안타 오태곤 오오오오랜더스의 승리 위해×2", "sk37.mp3", "SK:37"),
            new CheerSong("SK:31:sk31", "기본응원가", "워 워워워워 랜더스 이정범워 워워워 워워워 안타 날려버려×2", "sk31.mp3", "SK:31"),
            new CheerSong("SK:59:sk59", "기본응원가", "SSG 안방마님 이지영 안타!오 랜더스의 이지영 안타! 안타를 날려줘요이야이야이야이야x2", "sk59.mp3", "SK:59"),
            new CheerSong("SK:3:sk3", "기본응원가", "오 안타 정준재 치고 달려 정준재오 안타 정준재 랜더스의 정준재오 오오오오오 치고 달려 정준재오 오오오오오 랜더스의 정준재", "sk3.mp3", "SK:3"),
            new CheerSong("SK:20:sk20", "기본응원가", "조형우 워어어어 시원하게날려라 워어어어 짜릿하게넘겨라 워어어어 랜더스 조형우 ×2", "sk20.mp3", "SK:20"),
            new CheerSong("SK:14:sk14(1)", "기본응원가", "빠바바바바밤 최! 빠바바바바밤 정!빰빠라바라바라밤 최! 정! 홈! 런!×4", "sk14(1).mp3", "SK:14"),
            new CheerSong("SK:14:sk14(2)", "두번째 응원가", "오! 승리의 최정(최!정!홈!런!)오! 랜더스 최정(최!정!홈!런!)오오오오오 우리의 최정오오오 오오오 최정(최!정!홈!런!)×2", "sk14(2).mp3", "SK:14"),
            new CheerSong("SK:7:sk7", "기본응원가", "랜더스 최준우 안타!오오오오 오오오랜더스 최준우 안타!오오오오 최준우×2", "sk7.mp3", "SK:7"),
            new CheerSong("SK:54:sk54", "기본응원가", "최지훈 안타! 최지훈 안타! 오오 오 오오오최지훈 안타! 최지훈 안타! 랜더스의 승리 위하여×2", "sk54.mp3", "SK:54"),
            new CheerSong("SK:13:sk13", "기본응원가", "하! 재! 훈랜더스의! 하재훈 안타워어어어어 하재훈 안타랜더스의! 하재훈 안타승리를 위해 하재훈 안타×2", "sk13.mp3", "SK:13"),
            new CheerSong("SK:35:sk35", "기본응원가", "야 야 야 야한유섬 날려버려라(홈런!) (×2)한유섬 날려버려라×2", "sk35.mp3", "SK:35"),
                new CheerSong("SK:1:sk1", "기본응원가", "랜더스 박지환\n안타를 날려라\n워어어 워어어 워어어\n랜더스 박지환\n승리를 위하여\n워어어 워어어 워어어\n(박지환!)", "sk1.mp3", "SK:1"),
                new CheerSong("SK:47:sk47", "기본응원가", "김성욱 랜더스를 위해\n날려라 워어어\n랜더스 김성욱 안!타!\n김성욱 랜더스를 위해\n달려라 워어어\n랜더스 김성욱\n김성욱!", "sk47.mp3", "SK:47"),
                new CheerSong("OB:23:ob23", "기본응원가", "강승호 안타! 강승호 안타! 최강두산 강승호\n강승호 두산의 강승호 강! 승! 호! [X2]", "ob23.mp3", "OB:23"),
            new CheerSong("OB:45:ob45", "기본응원가", "김기연 안타날려라! 김기연 홈런날려라!\n베어스 승리 위해 오오오 김기연\n김기연 안타날려라! 김기연 홈런날려라!\n베어스의 승리 위하여 오 김! 기! 연!", "ob45.mp3", "OB:45"),
            new CheerSong("OB:27:ob27", "기본응원가", "두산의 김대한 안타! 안타 워어어어! [X4]", "ob27.mp3", "OB:27"),
            new CheerSong("OB:2:ob2", "기본응원가", "두산의 김민석 힘차게 치고 달려라!\n두산의 김민석 승리를 위해 날려라!\n오오오오오오오오 승리를 위해\n[X2]", "ob2.mp3", "OB:2"),
            new CheerSong("OB:10:ob10", "기본응원가", "최강! 두산! 김민혁! 최강! 두산! 김민혁!\n오오오오오오오 안타 날려라 [X2]", "ob10.mp3", "OB:10"),
            new CheerSong("OB:33:ob33", "기본응원가", "날려라 날 려라 날려라 두 산의 김인태\n안타 안타 김인태! 최! 강! 두! 산! 김인태! [X2]", "ob33.mp3", "OB:33"),
            new CheerSong("OB:32:ob32", "기본응원가", "두산! 승리를 위해 다같이 김재환!\n두산! 승리를 위해 오오오! 오오오! [X2]", "ob32.mp3", "OB:32"),
            new CheerSong("OB:14:ob14", "기본응원가", "안타를 날려주세요 두산의 안타 박계범\n안타를 날려주세요 저 멀리 안타 박계범\n최! 강! 두! 산! 박! 계! 범!\n안타를 날려주세요 두산의 안타 박계범", "ob14.mp3", "OB:14"),
            new CheerSong("OB:16:ob16", "기본응원가", "두산 박준영 안타 박준영 두산 박준영 오오 (박준영!)\n두산 박준영 안타 박준영 최강두산 박! 준! 영!", "ob16.mp3", "OB:16"),
            new CheerSong("OB:53:ob53", "기본응원가", "최강두산 양석환 안타날려라!\n최강두산 양석환 홈런날려라!\n워어어어어↗ 양석환 워어어어어→ 양석환\n워어어어어↗ 양석환 워우워어 양! 석! 환!", "ob53.mp3", "OB:53"),
            new CheerSong("OB:25:ob25", "기본응원가", "두산의 안방마님 양의지 (양의지!)\n두산의 안방마님 양의지 (양의지!)\n안타를 날려줘요 홈런을 날려줘요\n두산의 안방마님 양! 의! 지! [X2]", "ob25.mp3", "OB:25"),
            new CheerSong("OB:6:ob6", "기본응원가", "최강두산! 오명진! 안타를 날려라\n최강두산! 오명진! 홈런을 날려라\n최강두산! 오명진! 안타를 날려라\n최강두산 오!명진", "ob6.mp3", "OB:6"),
            new CheerSong("OB:13:ob13", "기본응원가", "찬란하게 빛날 최강두산 이유찬 (이유찬!)\n힘차게 날아올라라! 최강두산 이유찬! [X2]", "ob13.mp3", "OB:13"),
            new CheerSong("OB:22:ob22", "기본응원가", "오오오 두 산의 장승현!\n오오오 두 산의 장승현!\n힘차게 날 려라 오 장 승현\n오오오 두 산의 장승현!", "ob22.mp3", "OB:22"),
            new CheerSong("OB:31:ob31", "기본응원가", "수빈! 두산의 정수빈 수빈! 승리를 위하여\n수빈! 힘차게 치고 달려 최강두산 정수빈! [X2]", "ob31.mp3", "OB:31"),
            new CheerSong("OB:51:ob51", "기본응원가", "조수행! 조수행! 조수행! 조수행! 안타치고 도루하고 라라라라 라라라라라! 조! 수! 행! [X2]", "ob51.mp3", "OB:51"),
            new CheerSong("OB:8:ob8", "기본응원가", "최강두산 케이브 최강두산 케이브\n승리를 위해 모두외쳐라!\n오오오오오오 케! 이! 브![X2]", "ob8.mp3", "OB:8"),
                new CheerSong("OB:52:ob52", "기본응원가", "준순 준순\n박! 준! 순!\n준순 준순\n박! 준! 순!\n베어스의 승리를 위해\n좌측! 우측!\n날려버려라!", "ob52.mp3", "OB:52"),
                new CheerSong("KT:50:kt50(1)", "기본응원가", "kt wiz 강백호(호) kt wiz 강백호\n승리를(호)위하여(호) k t wi z 강 백 호", "kt50(1).mp3", "KT:50"),
            new CheerSong("KT:50:kt50(2)", "두번째 응원가", "강백호 오오 오오오 오오\n강백호 오오 오오오 홈런!", "kt50(2).mp3", "KT:50"),
            new CheerSong("KT:55:kt55", "기본응원가", "kt위즈 승리위해 강현우 워 워어어어\nkt위즈 안방마님 강현우 워 워어어어\nkt위즈 승리위해 강현우 워 워어어어\nkt위즈 안방마님 강현우 워 워어어어 강!현!우!", "kt55.mp3", "KT:55"),
            new CheerSong("KT:52:kt52(1)", "기본응원가", "kt 권동진 안타 kt 권동진 안타\n안타를 날려라 kt wiz 권동진 안타\nkt 권동진 안타 kt 권동진 안타\n날려버려 권동진 You can do it go!", "kt52(1).mp3", "KT:52"),
            new CheerSong("KT:52:kt52(2)", "두번째 응원가", "kt 위즈 승리위해 날려라 권동진 안타!\nKT위즈 철벽내야 권동진 오오오 안타!\nKT 위즈 승리위해 날려라 권동진 안타!\nKT 위즈 철벽내야 안! 타! 권!동진!", "kt52(2).mp3", "KT:52"),
            new CheerSong("KT:53:kt53", "기본응원가", "kt wiz 김민혁 날려버려 김민혁\nWe can come together\nWe can come together\n(간주) 안! 타! (간주) 안! 타!\n(간주) 김!민!혁!", "kt53.mp3", "KT:53"),
            new CheerSong("KT:7:kt7(1)", "기본응원가", "날려버려 김상수 야야야야야\n안타안타 김상수 야야야야야", "kt7(1).mp3", "KT:7"),
            new CheerSong("KT:7:kt7(2)", "두번째 응원가", "날려버려 안타 김상수\n날려버려 안타 김상수\n날려버려 안타 김상수 상수\n김상수 김상수 kt wiz 김상수\nkt wiz 승리 위해 워어\n김상수 김상수 kt wiz 김상수\nkt wiz 김상수 김상수!", "kt7(2).mp3", "KT:7"),
            new CheerSong("KT:24:kt24", "기본응원가", "kt 문상철 워우 워우워우워 )\nkt 문상철 워우 워우워우워\nkt 문상철 워우 워우워우워\n신나게 외쳐봅시다 문! 상! 철!", "kt24.mp3", "KT:24"),
            new CheerSong("KT:27:kt27", "기본응원가", "kt 배정대 나나나나나나\nkt 배정대 나나나나나나\nkt 배정대 나나나나나나\nkt wiz 승리를 위해\n1루 2루 3루 홈 빵야!", "kt27.mp3", "KT:27"),
            new CheerSong("KT:28:kt28", "기본응원가", "송민섭이 섭이섭이섭이\nkt wiz의 폭풍질주 송민섭", "kt28.mp3", "KT:28"),
            new CheerSong("KT:8:kt8", "기본응원가", "안치영 안타 워어어어 kt 승리를 위하여\n안타를 날려버려 시원하게\n안치영 안타 안치영 안타 워어어어\nkt 승리를 위하여 안타를 날려버려\n워 워 워 안!치!영!", "kt8.mp3", "KT:8"),
            new CheerSong("KT:23:kt23", "기본응원가", "안현민 워어어 워어어어\n안현민 워어어 워어어어\n안현민 워어어 워어어어\nk! t! 안현민!", "kt23.mp3", "KT:23"),
            new CheerSong("KT:4:kt4", "기본응원가", "오! 오! 오윤석\nkt wiz 오윤석\n날려버려 안타안타안타\nkt wiz 오윤석 안타!", "kt4.mp3", "KT:4"),
            new CheerSong("KT:36:kt36", "기본응원가", "오오오오오오오오오 kt 오재일 안타\n오오오오오오오오오 kt 오재일 홈런\n오오오오오오오오오 kt 오재일 안타\n오오오오오오오오오 kt 오재일 홈런 오!재!일!", "kt36.mp3", "KT:36"),
            new CheerSong("KT:34:kt34", "기본응원가", "오오오오오오오 이호연 안타\n오오오 이호연 안타\n케이티 이호연 안타를 날려버려\n오오오오오오오 이호연 안타\n오오오 이호연 안타\n케이티 이호연 안타를 날려버려 (이!호!연!)", "kt34.mp3", "KT:34"),
            new CheerSong("KT:22:kt22", "기본응원가", "KT의 장성우 워어어어워\nKT의 장성우 워어워어어\nKT의 장성우 워어어어워\n승리를 위하여 워워", "kt22.mp3", "KT:22"),
            new CheerSong("KT:56:kt56", "기본응원가", "장준원 워어어 장준원\n장준원 워어어 KT 승리를 위해\n안타를 날려라 장준원 장!준!원!", "kt56.mp3", "KT:56"),
            new CheerSong("KT:51:kt51", "기본응원가", "오 장진혁 오오오 오 장진혁\n안타를 날려라 kt wiz 승리를 위해 안타!\n안! 타! 장진혁!", "kt51.mp3", "KT:51"),
            new CheerSong("KT:14:kt14", "기본응원가", "안타를 날려버려 천성호 워어어\n홈런을 날려버려 천성호\n오오오 kt위즈 승리위해 천성호 안타 워어\n안타를 날려버려 천성호 워어어\n홈런을 날려버려 천성호\n오오오 kt위즈 승리위해 천성호 안타 워어어어 천!성!호!", "kt14.mp3", "KT:14"),
            new CheerSong("KT:13:kt13", "기본응원가", "kt 허경민 안타 허경민\nkt 허경민 안타 허경민\n나나나나 나나나 나나나\nkt 승리를 위하여", "kt13.mp3", "KT:13"),
            new CheerSong("KT:10:kt10", "기본응원가", "황재균 황재균 kt wiz 황재균 워어\n승리를 위하여 날!려!버!려! 황!재!균!\n황재균 황재균 kt wiz의 황재균 워어\n안타! 홈런! 날려버려 kt 황재균!", "kt10.mp3", "KT:10"),
                new CheerSong("KT:33:kt33", "기본응원가", "KT 이정훈 워어어\n날려버려 이정훈\nKT의 승리를 위하여\n안타 워어어\n이! 정! 훈!", "kt33.mp3", "KT:33"),
                new CheerSong("KT:3:kt3", "기본응원가", "앤드류 스티븐슨\n아이야이야\n앤드류 스티븐슨\n아이야이야\n앤드류 스티븐슨\n아이야이야\n앤드류 스티븐슨\n아이야이야 헤이!", "kt3.mp3", "KT:3"),
                new CheerSong("WO:44:wo44", "기본응원가", "고!영우 승리위해 안타 날려버려\n고!영우 승리를 위해\n오오오 고영우 오오오 고영우 오오오 고영우 워어어어\n고!영우 승리위해 안타 날려버려\n고!영우 승리를 위해\n오오오 고영우 오오오 고영우 오오오 고영우 워어어어", "wo44.mp3", "WO:44"),
            new CheerSong("WO:12:wo12", "기본응원가", "안타! 안타! 안타! 김건희!\n키움 히어로즈 김건희 오 히어로즈 김건희\n안방마님 김건희 오오오 김!건!희!\n키움 히어로즈 김건희 오 히어로즈 김건희\n안방마님 김건희 오오오 김!건!희!", "wo12.mp3", "WO:12"),
            new CheerSong("WO:38:wo38", "기본응원가", "김동엽 워어어어 홈런! 김동엽 워어어어 홈런!\n승리의 영웅이 되리 김동엽\n김동엽 워어어어 홈런! 김동엽 워어어어 홈런!\n승리의 영웅이 되리 김동엽", "wo38.mp3", "WO:38"),
            new CheerSong("WO:47:wo47", "기본응원가", "히어로 김 (김!) 동 (동!) 헌 (헌!) 오오오 오오오\n히어로 김 (김!) 동 (동!) 헌 (헌!) 오오오 오오오\n히어로 김 (김!) 동 (동!) 헌 (헌!) 오오오 오오오\n히어로 김 (김!) 동 (동!) 헌 (헌!) 오오오 오오오", "wo47.mp3", "WO:47"),
            new CheerSong("WO:10:wo10", "기본응원가", "김웅빈 김웅빈 히어로즈 김웅빈\n히어로즈 승리를 위하여 날려버려 저멀리\n김웅빈 김웅빈 히어로즈 김웅빈\n히어로즈 승리를 위하여 날려버려 저멀리", "wo10.mp3", "WO:10"),
            new CheerSong("WO:32:wo32", "기본응원가", "오! 김재현 다함께 외쳐라\n라라랄라라라 랄랄라라 안타 김재현 (안타!)\n오! 김재현 다함께 외쳐라\n라라랄라라라 랄랄라라 안타 김재현 (안타!)", "wo32.mp3", "WO:32"),
            new CheerSong("WO:1:wo1", "기본응원가", "키움 김태진 워어어어 (안!타! 김!태!진!)\n키움 김태진 워어어어 (안!타! 김!태!진!)\n키움 김태진 워어어어 (안!타! 김!태!진!)\n키움 김태진 워어어어 (안!타! 김!태!진!)", "wo1.mp3", "WO:1"),
            new CheerSong("WO:14:wo14", "기본응원가", "박수 박수 박수종 안타 안타 박수종\n승리를 위하여 파이팅 키움 히어로 박수종\n박수 박수 박수종 안타 안타 박수종\n승리를 위하여 파이팅 키움 히어로 박수종", "wo14.mp3", "WO:14"),
            new CheerSong("WO:57:wo57", "기본응원가", "워어! 워어! 히어로즈 박주홍\n워어! 워어! 히어로즈 박주홍\n워어! 워어! 히어로즈 박주홍\n워어! 워어! 히어로즈 박주홍", "wo57.mp3", "WO:57"),
            new CheerSong("WO:48:wo48", "기본응원가", "히어로 박찬혁 워어어어\n히어로 박찬혁 워어어어\n히어로 박찬혁 워어어어\n히어로 박찬혁 워어어어", "wo48.mp3", "WO:48"),
            new CheerSong("WO:9:wo9", "기본응원가", "워어어 히어로 히어로 변상권\n안타 날려버려 날려버려라\n워어어 히어로 히어로 변상권\n키움 승리위해 날려버려라\n워어어 히어로 히어로 변상권\n안타 날려버려 날려버려라\n워어어 히어로 히어로 변상권\n키움 승리위해 날려버려라", "wo9.mp3", "WO:9"),
            new CheerSong("WO:24:wo24", "기본응원가", "날!려!라! 키움의 송성문 승리의 문을 열자 랄!랄!라!\n날!려!라! 키움의 송성문 승리의 문을 열자 (송!성!문!)\n날!려!라! 키움의 송성문 승리의 문을 열자 랄!랄!라!\n날!려!라! 키움의 송성문 승리의 문을 열자 (송!성!문!)", "wo24.mp3", "WO:24"),
            new CheerSong("WO:93:wo93", "기본응원가", "히어로즈의 여동욱 히어로즈의 여동욱\n승리를 위하여 움직여라 오오 여동욱\n히어로즈의 여동욱 히어로즈의 여동욱\n승리를 위하여 큰거한방 오오 여동욱", "wo93.mp3", "WO:93"),
            new CheerSong("WO:60:wo60", "기본응원가", "오! 오선진 히어로즈 오선진\n오오 오오오오 날! 려! 버! 려! 오선진!\n오! 오선진 히어로즈 오선진\n오오 오오오오 날! 려! 버! 려! 오선진!", "wo60.mp3", "WO:60"),
            new CheerSong("WO:15:wo15", "기본응원가", "히어로즈 승리위해 안타 이용규\n히어로즈 승리를 위하여 이용규 YOU! YOU! YOU!\n히어로즈 승리위해 안타 이용규\n히어로즈 승리를 위하여 이용규 YOU! YOU! YOU!", "wo15.mp3", "WO:15"),
            new CheerSong("WO:17:wo17", "기본응원가", "히어로즈 이원석 (안타!) 히어로즈 이원석 (안타!)\n히어로즈 이원석 오오오오 이원석\n히어로즈 이원석 (안타!) 히어로즈 이원석 (안타!)\n히어로즈 이원석 오오오오 이원석", "wo17.mp3", "WO:17"),
            new CheerSong("WO:5:wo5", "기본응원가", "히어로즈 이재상 히어로즈 이재상\n승리를 위해 치고 달려라 히어로 이재상 워어\n히어로즈 이재상 히어로즈 이재상\n승리를 위해 치고 달려라 히어로 이재상", "wo5.mp3", "WO:5"),
            new CheerSong("WO:58:wo58", "기본응원가", "이주형 워어어 이주형 워어어\n저 높이 날아올라 빛이 되리라 히어로즈 이주형\n이주형 워어어 이주형 워어어\n저 높이 날아올라 빛이 되리라 히어로즈 이주형", "wo58.mp3", "WO:58"),
            new CheerSong("WO:36:wo36", "기본응원가", "히어로즈 이형종 워어어 워어어어\n히어로즈 이형종 워어어 워어어어\n히어로즈 이형종 워어어 워어어어\n히어로즈 이형종 워어어 워어어어", "wo36.mp3", "WO:36"),
            new CheerSong("WO:6:wo6", "기본응원가", "임병욱 (짝짝짝짝) 임병욱 (짝짝짝짝)\n히어로즈의 승리를 위하여 하나되어 외쳐보자 (짝짝짝짝)\n임병욱 (짝짝짝짝) 임병욱 (짝짝짝짝)\n히어로즈의 승리를 위하여 하나되어 외쳐보자 (짝짝짝짝)", "wo6.mp3", "WO:6"),
            new CheerSong("WO:29:wo29", "기본응원가", "히어로즈 임지열 히어로즈 임지열\n히어로즈 Vamos 임지열 워어어어어\n히어로즈 임지열 히어로즈 임지열\n히어로즈 Vamos 임지열 워어어어어", "wo29.mp3", "WO:29"),
            new CheerSong("WO:61:wo61", "기본응원가", "오 히어로 장재영 오 히어로 장재영\n오 승리를 위하여 날아올라라\n히어로 장재영 히어로 장재영\n히어로는 바로 너 장재영 장!재!영!\n오 히어로 장재영 오 히어로 장재영\n오 승리를 위하여 날아올라라\n히어로 장재영 히어로 장재영\n히어로는 바로 너 장재영 장!재!영!", "wo61.mp3", "WO:61"),
            new CheerSong("WO:97:wo97", "기본응원가", "히어로 전태현 히어로즈 전태현\n승리를 위해 전태현 라랄랄라\n히어로 전태현 히어로즈 전태현\n승리를 위해 전태현 라랄랄라라", "wo97.mp3", "WO:97"),
            new CheerSong("WO:53:wo53", "기본응원가", "최주환 히어로즈의 최주환 안타 날려버려 워어어\n최주환 히어로즈의 최주환 안타 날려버려 워어어\n최주환 히어로즈의 최주환 안타 날려버려 워어어\n최주환 히어로즈의 최주환 안타 날려버려 워어어", "wo53.mp3", "WO:53"),
            new CheerSong("WO:4:wo4", "기본응원가", "히어로즈의 카디네스 승리를 위해 워어어어\n히어로즈의 카디네스 오 루벤 카디네스\n히어로즈의 카디네스 승리를 위해 워어어어\n히어로즈의 카디네스 오 루벤 카디네스", "wo4.mp3", "WO:4"),
            new CheerSong("HT:57:ht57", "기본응원가", "오오오 날려라 KIA 고종욱\n오오오 날려라 KIA 고종욱\n승리 위해 Go! Go! Go!\n날려라 KIA 고종욱\n오오오 날려라 KIA 고종욱\n오오오 날려라 KIA 고종욱\n승리 위해 Go! Go! Go!\n날려라 KIA 고종욱", "ht57.mp3", "HT:57"),
            new CheerSong("HT:14:ht14", "기본응원가", "KIA 김규성\n타이거즈 김규성\n최강 KIA 승리를 위하여\n날려버려라\nKIA 김규성\n타이거즈 김규성\n최강 KIA 승리를 위하여\nKIA! 김!규!성!", "ht14.mp3", "HT:14"),
            new CheerSong("HT:5:ht5", "기본응원가", "김도영 힘차게 날려라 KIA의 승리를 위하여 워어어어 워우워 날려라×2", "ht5.mp3", "HT:5"),
            new CheerSong("HT:35:ht35", "기본응원가", "최강 KIA의 김석환 안타\n최강 KIA의 김석환 안타\n워어 워어어어어어\n최강 KIA 김석환 안타\n최강 KIA의 김석환 안타\n최강 KIA의 김석환 안타\n워어 워어어어어어\n최강 KIA 김석환 안타", "ht35.mp3", "HT:35"),
            new CheerSong("HT:3:ht3", "기본응원가", "KIA의 김선빈\n안타 워어어어 (김!선!빈!)\nKIA의 김선빈\n안타 워어어 어어어 (김!선!빈!)\nKIA의 김선빈\n안타 워어어어 (김!선!빈!)\nKIA의 김선빈\n안타 워어어 어어어 (김!선!빈!)", "ht3.mp3", "HT:3"),
            new CheerSong("HT:42:ht42", "기본응원가", "KIA의 김태군 (안타!)\n김태군 (홈런!) 타이거즈 김태군\n승리를 부르는 KIA의 남자 김태군 워어어어\nKIA의 김태군 (안타!)\n김태군 (홈런!) 타이거즈 김태군\n승리를 부르는 KIA의 남자 김태군 워어어어", "ht42.mp3", "HT:42"),
            new CheerSong("HT:27:ht27", "기본응원가", "오오오 김호령 오오오오 김호령\n호령 호령 김호령 타이거즈 김호령\n오오오 김호령 오오오오 김호령\n호령 호령 김호령 타이거즈 김호령 화이팅!", "ht27.mp3", "HT:27"),
            new CheerSong("HT:47:ht47", "기본응원가", "타이거즈 나성범 안타\n안타 날려라 날려라 나! 성! 범!\n타이거즈 나성범 안타\n오오 오 오 오오오\n타이거즈 나성범 홈런\n홈런 날려라 날려라 나! 성! 범!\n타이거즈 나성범 홈런\n오오 오 오 오오오", "ht47.mp3", "HT:47"),
            new CheerSong("HT:36:ht36", "기본응원가", "밀어도 안타 당겨도 안타\n날려라 안타 박!재!현!\n밀어도 안타 당겨도 안타\n날려라 안타 박!재!현!\n(리듬음악) 안! 타!\n(리듬음악) 박!재!현!", "ht36.mp3", "HT:36"),
            new CheerSong("HT:15:ht15", "기본응원가", "자달릴까 타이거즈 박정우\n워어어어어어 어어 KIA 박정우!\n날려버려라 타이거즈 박정우\n워어어어어어 어어 KIA 박정우!", "ht15.mp3", "HT:15"),
            new CheerSong("HT:1:ht1", "기본응원가", "Ho! KIA 박 찬호!\nHo! KIA 박 찬호!\nHo! 승리를 위해!\n타! 이! 거! 즈! 박! 찬! 호!", "ht1.mp3", "HT:1"),
            new CheerSong("HT:29:ht29", "기본응원가", "타이거즈의 변우혁 안타\n날려버려라 변우혁 홈런\n타이거즈의 변우혁 안타\n날려버려라 변우혁 홈런\n날려버려라 워워우워워\n변우혁 안타 워워우워워\n날려버려라 워워우워워\n변우혁 홈런 워워우워워", "ht29.mp3", "HT:29"),
            new CheerSong("HT:58:ht58", "기본응원가", "KIA의 서건창 안타! 서건창 안타!\n워어어어어\nKIA의 서건창 안타! 서건창 안타!\n워어어어", "ht58.mp3", "HT:58"),
            new CheerSong("HT:56:ht56", "기본응원가", "오오 기아 오선우 나나나나\n안타 날려라 홈런 날려라 승리를 위해\n오오 기아 오선우 나나나나\n타이거즈 승리를 위해 워우워우 오!선!우!", "ht56.mp3", "HT:56"),
            new CheerSong("HT:45:ht45", "기본응원가", "홈런 KIA 위즈덤\n힘차게 날려라 워우워우\n홈런 KIA 위즈덤\n승리를 위하여 워우워우\n홈런 KIA 위즈덤\n힘차게 날려라 워우워우\n홈런 KIA 위즈덤\n승리를 위하여 워우워우", "ht45.mp3", "HT:45"),
            new CheerSong("HT:9:ht9", "기본응원가", "안!타! 최강 KIA 윤도현\n홈!런! 타이거즈 윤도현\n승리를 위하여 오오오오 오오 오오\n안!타! 최강 KIA 윤도현\n홈!런! 타이거즈 윤도현\n승리를 위하여 오오오오 오오 오오", "ht9.mp3", "HT:9"),
            new CheerSong("HT:8:ht8", "기본응원가", "안 타 워어 KIA 이창진\n홈런 워어 KIA 이창진\n승리를 위해 다같이 외쳐 KIA! 이창진!", "ht8.mp3", "HT:8"),
            new CheerSong("HT:22:ht22", "기본응원가", "워 워 시원하게 안타\n화끈하게 홈런 KIA 주효상\n날려버려라 승리를 위하여\n워우워우워우워\n워 워 시원하게 안타\n화끈하게 홈런 KIA 주효상\n날려버려라 승리를 위하여\nKIA! 주!효!상!", "ht22.mp3", "HT:22"),
            new CheerSong("HT:34:ht34(1)", "기본응원가", "최강 KIA 타이거즈 최형우 (최!형!우!)\n최강 KIA 타이거즈 최형우 (최!형!우!)\n워 최형우 워 최형우 워 최형우 KIA의 해결사!", "ht34(1).mp3", "HT:34"),
            new CheerSong("HT:34:ht34(2)", "두번째 응원가", "(This is Our House) KIA! 최형우!\n(This is Our House) KIA! 최형우!\n워어어어어 KIA! 최형우!\n워어어어어 KIA! 최형우!", "ht34(2).mp3", "HT:34"),
            new CheerSong("HT:26:ht26", "기본응원가", "KIA 한승택 KIA의 안방마님 한승택 워어\nKIA 한승택 한승택 워어어 워어어", "ht26.mp3", "HT:26"),
            new CheerSong("HT:55:ht55", "기본응원가", "기아의 한준수 워어어 어어어어\n날려라 한준수 워어어어어\nKIA의 한준수 워어어 어어어어\n날려라 한준수 워어어어어\nKIA의 한준수 워어어 어어어어\n날려라 한준수 워어어어어\nKIA의 한준수 워어어 어어어어\n날려라 한준수 워어어어어", "ht55.mp3", "HT:55"),
            new CheerSong("HT:6:ht6", "기본응원가", "날려라 홍종표 달려라 홍종표 기아의 날쌘돌이 홍종표\n승리를 위하여 달려간다 워어 타이거즈 홍종표\n날려라 홍종표 달려라 홍종표 기아의 날쌘돌이 홍종표\n승리를 위하여 치고 달려라 기!아! 홍종표!", "ht6.mp3", "HT:6"),
            new CheerSong("HT:52:ht52", "기본응원가", "안타를 날려라 홈런을 날려라\n오오오 KIA 타이거즈 황대인\n승리를 위하여 다함께 외쳐라\n안타! 홈런! 황!대!인! ×2", "ht52.mp3", "HT:52"),
                new CheerSong("HT:2:ht2", "기본응원가", "타이거즈의 박민\n워어어어\n안타 홈런 날려버려 워우어\n기아 승리를 위해 달려\n박! 민! [X2]\n영원토록 달려갈거야", "ht2.mp3", "HT:2")
        );

        cheerSongRepository.saveAll(cheerSongs);
        log.info("🎵 Loaded {} cheer songs", cheerSongs.size());
    }
}
